# Generated by Django 4.2.5 on 2023-09-17 07:25

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("intro", models.TextField()),
                ("content", mdeditor.fields.MDTextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
