# Generated by Django 4.2.5 on 2023-09-17 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="Blogs",
        ),
    ]
